#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# aimail bootstrap — one-shot install of the aimail CLI + machine init.
#
#   curl -fsSL https://raw.githubusercontent.com/metercai/aimail/main/scripts/bootstrap.sh | bash
#
# What it does (all writes confined to ~/.aimail and ~/.local/bin, no sudo):
#   1. preflight: python3 >= 3.10, curl, tar, gzip
#   2. build the machine main dir ~/.aimail (0700) — idempotent
#   3. disk headroom check (<100 MiB fail, <1 GiB warn)
#   4. fetch the aimail toolkit (codeload tarball; AIMAIL_VERSION to pin a
#      tag, default main) into ~/.aimail/toolkit/aimail-src
#   5. link ~/.local/bin/aimail → toolkit cli/aimail (PATH hint if needed)
#   6. machine init: aimail init (gateway discovery / direct-vs-bridge /
#      bridge skeleton) — reads AIMAIL_URL from ~/.aimail/.env when present
#   7. next-step guidance (aimail install --home …  →  welcome)
#
# Re-running = upgrade (re-fetch toolkit) + init re-check.
#   AIMAIL_SKIP_INSTALL=1   → only re-init an existing install
#   AIMAIL_TOOLKIT_DIR=…    → custom toolkit dir (default ~/.aimail/toolkit)
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

# All output to stderr: under `curl … | bash` stdout is a pipe (block
# buffered) — buffered output would only flush at exit, so a slow/hung
# download would show nothing on screen. stderr is unbuffered.
exec 1>&2

# Single authoritative layout: ~/.aimail (bridge/CLI share it; the local
# bridge is a machine-level single instance, not per-home). Customize the
# toolkit location only via AIMAIL_TOOLKIT_DIR.
AM_HOME="$HOME/.aimail"
TOOLKIT="${AIMAIL_TOOLKIT_DIR:-$AM_HOME/toolkit}"
SRC="$TOOLKIT/aimail-src"
BIN_DIR="$HOME/.local/bin"
REF="${AIMAIL_VERSION:-main}"
DL="https://codeload.github.com/metercai/aimail/tar.gz/refs/heads/$REF"

say()  { printf '  %s\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m⚠ %s\033[0m\n' "$*"; }
die()  { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# ── 1. preflight ───────────────────────────────────────────────────
command -v python3 >/dev/null || die "python3 required (>= 3.10)"
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' \
  || die "python3 >= 3.10 required (found $(python3 --version 2>&1 | awk '{print $2}'))"
command -v curl >/dev/null || die "curl required"
command -v tar  >/dev/null || die "tar required"

# ── 2. main dir (0700 — holds admin keys/secrets) ──────────────────
mkdir -p "$AM_HOME" "$AM_HOME/systems" "$AM_HOME/logs" "$AM_HOME/bridge"
chmod 700 "$AM_HOME" 2>/dev/null || true
ok "main dir $AM_HOME"

# ── 3. disk headroom ───────────────────────────────────────────────
FREE_MIB=$(( $(df -Pk "$AM_HOME" | awk 'NR==2 {print $4}') / 1024 ))
if [ "$FREE_MIB" -lt 100 ]; then
  die "insufficient free disk on $AM_HOME: ${FREE_MIB} MiB (< 100 MiB)"
elif [ "$FREE_MIB" -lt 1024 ]; then
  warn "low free disk on $AM_HOME: ${FREE_MIB} MiB — watch logs/mail snapshots"
else
  ok "disk free: ${FREE_MIB} MiB"
fi

# ── 4. toolkit (idempotent: present → skip; FORCE_UPGRADE=1 to re-fetch) ──
if [ "${AIMAIL_SKIP_INSTALL:-0}" = "1" ]; then
  [ -x "$SRC/cli/aimail" ] || die "AIMAIL_SKIP_INSTALL=1 but no toolkit at $SRC"
  ok "toolkit present (skip-install)"
elif [ -x "$SRC/cli/aimail" ] && [ "${AIMAIL_FORCE_UPGRADE:-0}" != "1" ]; then
  ok "toolkit up-to-date ($REF) — AIMAIL_FORCE_UPGRADE=1 re-fetches"
else
  TMP_TGZ="$(mktemp /tmp/aimail-bootstrap-XXXXXX.tar.gz)"
  trap 'rm -f "$TMP_TGZ"' EXIT
  say "fetching aimail@$REF …"
  curl -fsSL --retry 2 --retry-delay 2 --connect-timeout 15 --max-time 180 \
    "$DL" -o "$TMP_TGZ" || die "download failed: $DL"
  mkdir -p "$TOOLKIT"
  EXTRACTED="$(mktemp -d /tmp/aimail-x-XXXXXX)"
  tar -xzf "$TMP_TGZ" -C "$EXTRACTED" || die "extract failed"
  SRC_NEW="$EXTRACTED/aimail-$REF"
  [ -d "$SRC_NEW" ] || SRC_NEW="$(find "$EXTRACTED" -maxdepth 1 -type d -name 'aimail-*' | head -1)"
  [ -x "$SRC_NEW/cli/aimail" ] || die "toolkit tarball has no cli/aimail"
  rm -rf "$SRC"                        # atomic-ish swap
  mv "$SRC_NEW" "$SRC"
  rm -rf "$EXTRACTED"
  chmod +x "$SRC/cli/aimail"
  ok "toolkit installed at $SRC (ref=$REF)"
fi

# ── 5. PATH entry ──────────────────────────────────────────────────
mkdir -p "$BIN_DIR"
ln -sf "$SRC/cli/aimail" "$BIN_DIR/aimail"
ok "linked $BIN_DIR/aimail"
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) warn "add to PATH: export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac

# ── 5.5 persist shell env vars into ~/.aimail/.env (future terminals) ─
# Only AIMAIL_* keys set in this shell are written; existing keys in the
# file are never overwritten. The file lives in the 0700 main dir.
ENV_FILE="$AM_HOME/.env"
(
  [ -f "$ENV_FILE" ] || printf '# aimail machine env — generated by bootstrap\n' >> "$ENV_FILE"
  for k in AIMAIL_URL AIMAIL_MANAGER_ADDRESS AIMAIL_ADMIN_KEY \
           AIMAIL_PRODUCT_CODE AIMAIL_SYSTEM_NAME AIMAIL_DOMAIN \
           AIMAIL_WEBHOOK_HOST AIMAIL_WEBHOOK_MODE; do
    v="${!k:-}"
    if [ -n "$v" ] && ! grep -q "^$k=" "$ENV_FILE" 2>/dev/null; then
      printf '%s=%s\n' "$k" "$v" >> "$ENV_FILE"
    fi
  done
)
chmod 600 "$ENV_FILE" 2>/dev/null || true
[ -f "$ENV_FILE" ] && ok "env persisted to $ENV_FILE"

# ── 5.6 env readiness (README scenarios A/B/C; set env BEFORE bootstrapping)
have_env() { [ -n "${!1:-}" ] || grep -q "^$1=" "$ENV_FILE" 2>/dev/null; }
if have_env AIMAIL_URL && \
   { { have_env AIMAIL_PRODUCT_CODE && have_env AIMAIL_SYSTEM_NAME; } || \
     { have_env AIMAIL_PRODUCT_CODE && have_env AIMAIL_DOMAIN; } || \
     { have_env AIMAIL_ADMIN_KEY && have_env AIMAIL_DOMAIN; }; }; then
  ok "env ready (one of the README scenarios)"
else
  warn "env incomplete — see README (bootstrap prerequisites) for the AIMAIL_* set, then re-run"
fi

# ── 6. machine init (idempotent: .env + bridge binary present → skip) ─
ENV_READY=0
[ -f "$AM_HOME/.env" ] && ENV_READY=1
BRIDGE_READY=0
[ -x "$AM_HOME/bridge/bin/aimail-bridge" ] && BRIDGE_READY=1
if [ "$ENV_READY" = "1" ] && [ "$BRIDGE_READY" = "1" ] && [ "${AIMAIL_FORCE_UPGRADE:-0}" != "1" ]; then
  ok "machine init already done (.env + bridge binary present) — re-run with AIMAIL_FORCE_UPGRADE=1 to re-check"
else
  if [ ! -f "$AM_HOME/.env" ]; then
    warn "no env values set yet — export them first (AIMAIL_URL + manager),"
    warn "or create $AM_HOME/.env by hand; running init with defaults"
    warn "(gateway probe / default aimail.token.tm)"
  fi
  "$BIN_DIR/aimail" init || warn "init reported problems — see above"
fi

# ── 7. next steps ──────────────────────────────────────────────────
echo
ok "bootstrap done — aimail $(cd "$SRC" && git describe --tags 2>/dev/null || echo "$REF")"
say "next:"
say "  1. activate a system: →  aimail install --home <agent-host-root>"
say "  2. verify the loop:   →  aimail welcome"
say "diagnose: aimail check · aimail stats"
